Doc: add getting-started tutorial
canonical/testflinger pull request #150
Opened 2023-10-27 12:48 UTC by tang-mm

## Description

Added a basic tutorial for first-time users of client, covering:
- installing the CLI via Snap
- configure the default server
- creating a first job
- submit job
- check job status
- check job output

## Resolved issues

Resolves [CERTTF-222](https://warthogs.atlassian.net/browse/CERTTF-222)

## Documentation

Preview version on Readthedocs:

https://canonical-testflinger.readthedocs-hosted.com/en/doc-preview/tutorial

## Tests

To check the documentation on a local sphinx site:
```
$ cd testflinger/docs
$ make install
$ make run     # Serve docs on http://127.0.0.1:8000/reference/test-phases/
```

2023-10-27 17:29 UTC, plars requested changes
Those preview links are super-helpful, thanks for including those!
This looks good other than some strange syntax highlighting. I would guess it could either be turned off for those code blocks or changed to some other type of highlighting.

2023-10-27 17:29 UTC, plars commented on docs/tutorial/index.rst
> +.. code-block:: shell
Can we remove the syntax highlighting from this section? It's highlighting some strange words in the preview build.

2023-10-27 17:29 UTC, plars commented on docs/tutorial/index.rst
> +.. code-block:: shell
Same here with the syntax highlighting. "for" gets highlighted below.

2023-11-16 17:57 UTC, plars approved these changes
It looks like the earlier section for testflinger-cli looks fine for me now since you removed "bash", but the later one still had weird highlighting.
![image](https://github.com/canonical/testflinger/assets/1255513/ab3dae7e-150f-4f93-81c5-f7427fda0108)

I found that if I use "text" instead, then it renders fine for me now. I hope you don't mind, I just pushed the change, since it was trivial. And I'm +1 on it now. But I'll let you make the final call :)

2023-11-23 09:44 UTC, kevinyehk approved these changes
LGTM +1

2023-11-27 13:37 UTC, merged