Riverside: Workaround PDU issue LP#2039983
canonical/testflinger pull request #160
Opened 2023-11-10 09:09 UTC by rmartin013

## Description

## Resolved issues

## Documentation

## Tests

2023-11-10 10:14 UTC, plars requested changes
The tests seem to just be failing due to the PR not being signed. Can you take a look at https://github.com/canonical/testflinger/blob/main/CONTRIBUTING.md and set up signing keys? Then there are some commands in that document which show you how to go back and sign your commits without having to start over completely

2023-11-10 12:42 UTC, rmartin013 commented
@plars I pushed again my change, making sure my commit is signed, but still I get an error. I guess this is something else now...

2023-11-14 14:21 UTC, plars commented
/canonical/self-hosted-runners/run-workflows dcbe9136d83f838401aad9d6bf5b6f6296bca50f

2023-11-14 14:51 UTC, plars commented
/canonical/self-hosted-runners/run-workflows 5daa12c597da59eee4bc4094192703a7dc92bd68

2023-11-14 14:55 UTC, plars commented
/canonical/self-hosted-runners/run-workflows a99048f0b1bd95f1d9b78030041e6e5ac178309c

2023-11-14 15:01 UTC, plars approved these changes
+1 thanks!

2023-11-14 15:01 UTC, merged