remove oem image once provision is completed
canonical/testflinger pull request #208
Opened 2024-02-27 08:37 UTC by nancyc12

## Description
Currently testflinger agent won't remove the .iso images from /testflingere/run folder once provision is completed. Propose to add a step to remove image file at the end of provision phase for oemscript devices.

## Resolved issues
Reduce the manual effort to clean up accumulated image files in /testflinger/run folder.

## Documentation

## Tests

2024-02-27 09:27 UTC, kevinyehk approved these changes
Thanks for fixing this promptly, but I think it still needs @plars 's approval.

2024-02-27 12:44 UTC, jocave reviewed
Seems like this could be a case for use of a context manager if we want to ensure cleanup happens even in an error situation.

2024-02-29 01:59 UTC, plars requested changes
Yeah, a context manager would be nice but since you're just getting back the filename, it might not be practical. At the very least, I would definitely just use os.unlink() (or os.remove()) rather than running it as a subprocess command.

To get pretty much the same benefit as a context manager here, you could also wrap everything from the download() through self.check_device_booted() in a `try` block, and use something like:
```
finally:
    os.unlink(image_file)
```
to ensure that it gets removed regardless of anything else that happens there.

2024-02-29 15:59 UTC, nancyc12 commented
Thank you @jocave and @plars  for the comments. It's truly something I missed.

2024-03-05 01:31 UTC, plars approved these changes
+1 thanks!

2024-03-05 02:19 UTC, merged