Add authentication to CLI when submitting jobs with priority
canonical/testflinger pull request #360
Opened 2024-09-12 18:02 UTC by val500

## Description

## Resolved issues

## Documentation

## Web service API changes

## Tests

2024-10-28 11:13 UTC, plars requested changes
Haven't looked at all of this yet, but I noticed the tests section is completely empty. Can we get more details on how you tested this? I think it's also good to have some sort of unit tests that cover the new code here too.

2024-10-28 16:18 UTC, val500 commented
> Haven't looked at all of this yet, but I noticed the tests section is completely empty. Can we get more details on how you tested this? I think it's also good to have some sort of unit tests that cover the new code here too.

Just added 2 unit tests - is there any other functionality you think it would be beneficial to test?

2024-10-31 12:48 UTC, plars requested changes
Just a couple of very minor things

2024-10-31 12:48 UTC, plars commented on docs/how-to/job-priority.rst
> +In order to use this field, you need to be :doc:`authenticated <./authentication>` with the server.
Small rephrase - "... you need an authorisation token from the server"

2024-10-31 12:48 UTC, plars commented on docs/reference/job-schema.rst
> +    - | (Optional) Integer specifying how much priority this job has. Jobs with higher job_priority will be selected by agents before other jobs. Specifying a job priority requires authorisation in t
This is where spelling differences get tricky. To follow guidelines, we should use the UK spelling. But AFAIK, "Authorization" is the spelling used in the RFC. To be more clear, when you're actually referring to the header, it should be the spelling with the 'z'.

2024-11-01 09:44 UTC, plars approved these changes
checkmate, +1 :)

2024-11-01 09:44 UTC, merged