Agent host terraform constraints
canonical/testflinger pull request #387
Opened 2024-10-27 17:08 UTC by plars

## Description

The existing terraform module doesn't allow specifying constraints for the virtual machine that should be deployed, if you are deploying this to something like LXD. This adds some reasonable defaults and also allows you to override them.

## Resolved issues
N/A

## Documentation
Covered the new options in the README.md

## Web service API changes
N/A

## Tests
Confirmed these options can be used to deploy a new instance, and also confirmed that overriding works properly if you have an old instance with some previous default like "arch=amd64" and need to keep it without terraform trying to remove/re-add it.

2024-10-30 09:37 UTC, nancyc12 requested changes
Thanks for making the changes to allow flexibility and consistency for maintenance :)
I only have some small suggestions about the indent in README to make them aligned.

2024-10-30 09:37 UTC, nancyc12 commented on agent/terraform/README.md
> +        $ juju add-model agent-host-1
```suggestion
    $ juju add-model agent-host-1
```

2024-10-30 09:37 UTC, nancyc12 commented on agent/terraform/README.md
> +        $ ssh-keygen -t rsa -f mykey
```suggestion
    $ ssh-keygen -t rsa -f mykey
```

2024-10-30 09:37 UTC, nancyc12 commented on agent/terraform/README.md
> +        $ terraform apply
```suggestion
    $ terraform init
    $ terraform apply
```

2024-11-01 20:49 UTC, plars commented on agent/terraform/README.md
> +        $ terraform apply
fixed

2024-11-01 20:49 UTC, plars commented on agent/terraform/README.md
> +        $ ssh-keygen -t rsa -f mykey
fixed

2024-11-01 20:50 UTC, plars commented on agent/terraform/README.md
> +        $ juju add-model agent-host-1
fixed

2024-11-01 20:50 UTC, plars commented
All fixed now I think, thanks!

2024-11-01 21:56 UTC, nancyc12 approved these changes

2024-11-04 16:47 UTC, merged