Create new script to create client credentials in MongoDB
canonical/testflinger pull request #388
Opened 2024-10-28 15:12 UTC by val500

## Description

## Resolved issues

## Documentation

## Web service API changes

## Tests

2024-10-29 14:39 UTC, plars requested changes
A few comments below, but a few more general comments:
1. please run flake8/pylint/black -n79 on this
2. There's a big problem I found - you can add the same client ID more than once. We shouldn't allow that
3. There should be some confirmation step at the end where it shows you what it's going to add (except the secret) and ask to confirm whether to add it or not

2024-10-29 14:39 UTC, plars commented on server/tools/client_credentials_admin.py
> +import bcrypt
we should go ahead and add this as a requirement on the server side since it's needed for this

2024-10-29 14:39 UTC, plars commented on server/tools/client_credentials_admin.py
> +    client_secret = input("Enter the new client_secret: ")
Lets use getpass for this

2024-10-29 14:39 UTC, plars commented on server/tools/client_credentials_admin.py
> +            queue_name = input("Enter the name of the queue: ")
```suggestion
            queue_name = input("Enter the name of the queue(* to apply max priority for all queues): "): ")
```

2024-10-29 14:39 UTC, plars commented on server/tools/client_credentials_admin.py
> +            "Do you want to specify a max priority for one or more queues? (y/n): "
I feel like the wording of this is unclear... maybe something more like "Specify a queue to set max priority on?" Unless you can think of something better?

2024-10-29 15:02 UTC, val500 commented on server/tools/client_credentials_admin.py
> +    return allowed_queues
Yeah not supported yet. I can change it so it also adds these listed queues to the restricted_queues collection.

2024-11-01 10:29 UTC, val500 commented on server/tools/client_credentials_admin.py
> +    return allowed_queues
I added a separate option to add/remove entries from that restricted_queues collection

2024-11-01 20:34 UTC, plars requested changes
Found a couple more small issues, and I think there were still some earlier comments.

Additionally, I had trouble making it work if you use pip install. I know we use poetry, but we still try to import pip install for the charm, previous way of doing things, etc. And both *should* work fine

I did solve this with a few minor changes. I can just submit a patch against your branch if you prefer... just let me know, but might be easier for you to make the other changes first. But here are the things I needed to change to get it working:
- move tools to src/tools
- add a src/tools/__init__.py
- pyproject.toml: add this under tool.poetry section:
```
+packages = [
+    { include = "src" },
+]
```
- set `client_credentials_admin = "src.tools.client_credentials_admin:main"` (added "src" to the path)

2024-11-01 20:34 UTC, plars commented on server/tools/client_credentials_admin.py
> +        confirm = input("Confirm(y/n) that this entry looks correct: ")
Put the (y/n) at the end to be consistent with the other prompts

2024-11-01 20:34 UTC, plars commented on server/tools/client_credentials_admin.py
> +        db.client_permissions.find_one_and_update(
There's no check to see if this actually updated something, and it didn't check that the client_id existed, so if you edit one that doesn't exist, then nothing happens but it also doesn't give you an error saying that it didn't exist

2024-11-08 03:49 UTC, plars approved these changes
Ok, I think this works well enough for our short term needs. It's something we'll replace with an API pretty soon I hope, but it'll get us though until then. Thanks!

2024-11-08 17:02 UTC, merged