Update credential script to add ability to set maximum reservation time
canonical/testflinger pull request #433
Opened 2024-12-20 00:40 UTC by val500

## Description

Updates the client credentials script to allow for adding max_reservation_time. Follows similar logic to the job_priority part of the script.

## Resolved issues
Resolves https://warthogs.atlassian.net/browse/CERTTF-459

## Documentation
N/A

## Web service API changes
N/A

## Tests
Tested locally with a local deployment of Testflinger Server/MongoDB

2025-01-13 02:03 UTC, plars reviewed
Looks ok, consistent with the other things at least. Needs the other part of this to land (see comments from George) and also seems to have a minor lint issue to fix

2025-01-17 21:53 UTC, plars requested changes
One minor thing in several places that I just noticed. it's worth cleaning up now while we wait on the other part to land.

2025-01-17 21:53 UTC, plars commented on server/src/tools/client_credentials_admin.py
> +            + " max reservation time for? (y/n): "
I just noticed this, because the + blended in with the other "+"s on the left :)
But you don't really need that + to concatenate the strings. Any string within parentheses is going to get automatically concatenated. This is similar to you how can handle things like line length limits by adding ()s and breaking a string across lines. It's a minor thing but let's go ahead and clean it up since we're also waiting for the other thing to land anyway.

2025-01-27 16:48 UTC, boukeas requested changes
Fine overall, just a couple of minor requests here and there.

2025-01-27 16:48 UTC, boukeas commented on server/src/tools/client_credentials_admin.py
> +            )
I know it's a little pedantic but I'd prefer:
```
            queue_name = input(
                "Enter the name of the queue ",
                "(* to apply max reservation  for all queues): ",
            )
```

2025-01-27 16:48 UTC, boukeas commented on server/src/tools/client_credentials_admin.py
> +            )
You might want to `try-except` for a `ValueError` here, it wouldn't be nice to collapse because the user mistypes something that can't be converted to a number.

2025-01-27 16:48 UTC, boukeas commented on server/src/tools/client_credentials_admin.py
> +        if max_reservation_input == "y":
I would suggest going for `max_reservation_input.lower()` here. Just a little more resilience in case the user types `Y` instead of `y`. Same below for `n`.

2025-01-28 07:46 UTC, boukeas approved these changes

2025-01-28 15:31 UTC, merged