[CERTTF-457] feat: Github action for retrieving data from multi-device jobs
canonical/testflinger pull request #434
Opened 2024-12-20 10:31 UTC by boukeas

## Description

This PR introduces a Testflinger Github action that polls a multi-device job (receiving its ID as its input) and returns the job IDs and machine IPs of its child jobs as a JSON string.

## Resolved issues

Resolves [CERTTF-457](https://warthogs.atlassian.net/browse/CERTTF-457).

## Tests

The workflow below was used to submit a multi-device job without polling, use the `poll-multi` action to retrieve the data for the child jobs, and then display that data and confirm it's valid JSON.

```
name: Temporary workflow for testing multi-device polling action
on:
  push:
  workflow_dispatch:

jobs:
  submit-and-poll:
    name: Submit multi-device job and poll it for its data
    runs-on: [self-hosted, testflinger]
    steps:

    - name: Submit job to Testflinger
      id: submit
      uses: canonical/testflinger/.github/actions/submit@main
      with:
        poll: false
        job: |
          job_queue: multi-1
          name: multi-device-job
          output_timeout: 43200
          provision_data:
            jobs: 
            - job_queue: 202407-34216
              name: dell-xps-13-9350-0cc9-c34216
              reserve_data:
                ssh_keys:
                - lp:boukeas
                timeout: 600
            - job_queue: 202008-28168
              name: hp-eliteone800-g627-all-in-one-pc-c28168
              reserve_data:
                ssh_keys:
                - lp:boukeas
                timeout: 600
    - name: Retrieve multi-device job data
      id: poll
      uses: canonical/testflinger/.github/actions/poll-multi@CERTTF-457-multi-device-polling
      with:
        job-id: ${{ steps.submit.outputs.id }}
    
    - name: Verify
      shell: bash
      env:
        JOBS: ${{ steps.poll.outputs.jobs }}
      run: |
        echo $JOBS
        echo $JOBS | jq
```
Here is a [successful test run](https://github.com/canonical/certification-lab-ci/actions/runs/12429235502). This is the output of the action:
```
{
  "7fcc82b1-1ab8-4fcc-9e3f-b0f9afbcec49": "10.102.182.56",
  "52fa5098-eb7d-4084-b9b0-b830214c089f": "10.102.161.241"
}
```
A syntactically incorrect version of the job was [also submitted](https://github.com/canonical/certification-lab-ci/actions/runs/12428851840), to test that the action detects provisioning (i.e. allocation) failures for multi-device jobs.

2025-01-20 13:46 UTC, marosg42 commented
Hi George, sorry about the late response.
What we do currently is we generate a file for each agent.
```
job_queue: {{ job_queue }}
name: {{ job_name }}
provision_data:
    distro: {{ distro_series }}
    disks:
      - id: disk0
        disk: 0
        type: disk
        ptable: gpt
        name: disk0
   ...
reserve_data:
    ssh_keys:
      - lp:oil-ci-bot
    timeout: 21600
```
- where do I specify distro_series? I am assuming it is on individual job level
- regarding disks definition, do I put it to main job provision_data or do I have to put it to each individual job ?
- is `job_queue: multi-1` in your example real multidevice queue or is it just a descriptive string?

2025-01-20 14:38 UTC, marosg42 commented
I think I am using agent and queue terminology wrong in my thinking, let me do some tests and I will try to make better comments.

2025-01-20 15:07 UTC, marosg42 commented
@boukeas One important issue is that the job reports all done before devices are reserved

job output
```
{"35541dff-73d0-4a4f-b0d0-fc9a1cde2f56":"10.241.3.17","2c5e3c4b-886b-40c1-8e07-81795dddfb8a":"10.241.3.25","45ea63f1-551c-4bd1-a52f-cf7ea9237340":"10.241.3.26"}
{
  "35541dff-73d0-4a4f-b0d0-fc9a1cde2f56": "10.241.3.17",
  "2c5e3c4b-886b-40c1-8e07-81795dddfb8a": "10.241.3.25",
  "45ea63f1-551c-4bd1-a52f-cf7ea9237340": "10.241.3.26"
}
```

status of jobs in Testflinger
```
45ea63f1-551c-4bd1-a52f-cf7ea9237340	elvey	allocated	2025-01-20 15:02:17
2c5e3c4b-886b-40c1-8e07-81795dddfb8a	eevee	allocated	2025-01-20 15:02:17
35541dff-73d0-4a4f-b0d0-fc9a1cde2f56	ditto	allocated	2025-01-20 15:02:17
d1757fcc-2539-47d5-8464-09d667736cfb	multi-1	complete	2025-01-20 15:02:00
```

2025-02-03 19:17 UTC, marosg42 requested changes
Hello George. Looks good, I had a deployment which did what I wanted. One change request though, regarding output. Currently it outputs
```
{
  "c36e1fd2-307f-48c2-932a-f13b5666f6f8": "10.241.5.21",
  "b1429eb6-8ef7-4af8-9c31-1a1d6cbe470a": "10.241.3.36",
  "8ef2fdcb-e743-44d2-bb90-ea9a8528d46b": "10.241.5.[11]
}
```
Could you please change it this?
```
[
{ "device-ip": "10.241.5.21", "id": "c36e1fd2-307f-48c2-932a-f13b5666f6f8" },
{ "device-ip": "10.241.3.36", "id": "b1429eb6-8ef7-4af8-9c31-1a1d6cbe470a"}, 
{ "device-ip": "10.241.5.11", "id": "8ef2fdcb-e743-44d2-bb90-ea9a8528d46b"} 
]
```

2025-02-03 20:07 UTC, boukeas commented
> One change request though, regarding output. 

Should be good now @marosg42, if you'd like to run another test.

2025-02-04 10:06 UTC, marosg42 approved these changes
It works as expected, thank you.

2025-02-04 10:23 UTC, merged